# Generated by Django 5.2.6 on 2025-09-18 16:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spashtuser',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='spashtuser',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
